org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod_display_name=Random Nibble6Plus24 Generator
mod_id=randomnibble6plus24generator
mod_namespace=randomnibble6plus24generator
maven_group=io.github.recrivenvi
artifact_base_name=randomnibble6plus24generator
mod_author=RecRivenVI
mod_version=0.0.0-dev
